
const postedCases = [
  {
    _id: "6-2023",
    confirmedCases: 5,
    postedCases: 15,
    sumDeliveredAmounts: 20000,
    completeCases: 5,
    confirmedToUnlock: 5,
  },
  {
    _id: "5-2023",
    confirmedCases: 4,
    postedCases: 15,
    sumDeliveredAmounts: 15000,
    completeCases: 3,
    confirmedToUnlock: 2,
  },
  {
    _id: "4-2023",
    confirmedCases: 6,
    postedCases: 24,
    sumDeliveredAmounts: 12000,
    completeCases: 1,
    confirmedToUnlock: 1,
  },
  {
    _id: "3-2023",
    confirmedCases: 15,
    postedCases: 251,
    sumDeliveredAmounts: 36000,
    completeCases: 5,
    confirmedToUnlock: 5,
  },
  {
    _id: "2-2023",
    confirmedCases: 23,
    postedCases: 51,
    sumDeliveredAmounts: 25000,
    completeCases: 5,
    confirmedToUnlock: 5,
  },
  {
    _id: "1-2023",
    confirmedCases: 11,
    postedCases: 51,
    sumDeliveredAmounts: 15000,
    completeCases: 4,
    confirmedToUnlock: 4,
  },
  {
    _id: "12-2022",
    confirmedCases: 23,
    postedCases: 50,
    sumDeliveredAmounts: 18000,
    completeCases: 15,
    confirmedToUnlock: 15,
  },
  {
    _id: "11-2022",
    confirmedCases: 13,
    postedCases: 31,
    sumDeliveredAmounts: 21000,
    completeCases: 6,
    confirmedToUnlock: 7,
  },
  {
    _id: "10-2022",
    confirmedCases: 14,
    postedCases: 64,
    sumDeliveredAmounts: 25000,
    completeCases: 6,
    confirmedToUnlock: 9,
  },
  {
    _id: "9-2022",
    confirmedCases: 25,
    postedCases: 41,
    sumDeliveredAmounts: 30000,
    completeCases: 6,
    confirmedToUnlock: 8,
  },
  {
    _id: "8-2022",
    confirmedCases: 12,
    postedCases: 82,
    sumDeliveredAmounts: 15000,
    completeCases: 5,
    confirmedToUnlock: 7,
  },
  {
    _id: "7-2022",
    confirmedCases: 11,
    postedCases: 51,
    sumDeliveredAmounts: 26000,
    completeCases: 5,
    confirmedToUnlock: 6,
  },
];

const monthlyPostedCasesChart = [
  {
    _id: "6-2023",
    shortYear: "6-23",
    confirmedCases: 10,
    postedCases: 50,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "5-2023",
    shortYear: "5-23",
    confirmedCases: 5,
    postedCases: 250,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "4-2023",
    shortYear: "4-23",
    confirmedCases: 15,
    postedCases: 110,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "3-2023",
    shortYear: "3-23",
    confirmedCases: 60,
    postedCases: 50,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "2-2023",
    shortYear: "2-23",
    confirmedCases: 25,
    postedCases: 120,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "1-2023",
    shortYear: "1-23",
    confirmedCases: 5,
    postedCases: 70,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "12-2022",
    shortYear: "12-22",
    confirmedCases: 10,
    postedCases: 50,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "11-2022",
    shortYear: "11-22",
    confirmedCases: 31,
    postedCases: 60,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "10-2022",
    shortYear: "10-22",
    confirmedCases: 130,
    postedCases: 250,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "9-2022",
    shortYear: "9-22",
    confirmedCases: 10,
    postedCases: 50,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "8-2022",
    shortYear: "8-22",
    confirmedCases: 10,
    postedCases: 50,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
  {
    _id: "7-2022",
    shortYear: "7-22",
    confirmedCases: 201,
    postedCases: 350,
    sumRequestedAmounts: 200,
    numberOfCompleteCases: 5,
    numberOfConfirmedToUnlock: 5,
  },
];

export {postedCases, monthlyPostedCasesChart}